In [1]:
from bs4 import BeautifulSoup
import requests
import time
import pandas as pd
import numpy as np

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome()
driver.get('https://www.pianobuyer.com/new-piano-pricing')
import numpy as np

In [3]:
time.sleep(20)
trs = driver.find_elements(By.XPATH , '//*[@id="comp-l3ncpcyh"]/div/div/table/tbody/tr')
print(len(trs))

1000

In [4]:
brand = []
model = []
dimension = []
description = []
price = []
for i in range(1 , 1000):
    brand.append(trs[i].find_elements(By.XPATH, f'//*[@id="comp-l3ncpcyh"]/div/div/table/tbody/tr[{i}]/td[1]')[0].text)
    model.append(trs[i].find_elements(By.XPATH, f'//*[@id="comp-l3ncpcyh"]/div/div/table/tbody/tr[{i}]/td[2]')[0].text)
    dimension.append(trs[i].find_elements(By.XPATH, f'//*[@id="comp-l3ncpcyh"]/div/div/table/tbody/tr[{i}]/td[3]')[0].text)
    description.append(trs[i].find_elements(By.XPATH, f'//*[@id="comp-l3ncpcyh"]/div/div/table/tbody/tr[{i}]/td[5]')[0].text)
    price.append(trs[i].find_elements(By.XPATH, f'//*[@id="comp-l3ncpcyh"]/div/div/table/tbody/tr[{i}]/td[7]')[0].text)

In [5]:
type = ['grand']* 999

In [6]:
df = pd.DataFrame({"brand" : brand , "type" : type , "model" : model , "dimension" : dimension , "description" : description , "price" : price})

In [7]:
df

,brand,type,model,dimension,description,price
0,Cristofori,grand,G62L,6,Ebony Satin,"$20,318"
1,Fazioli,grand,F308,10,Ebony Polish/Satin,"$302,000"
2,Fazioli,grand,F308,10,White or Red Polish/Satin,"$332,300"
3,Fazioli,grand,F308,10,"Walnut, Cherry, or Mahogany Satin/Polish","$362,500"
4,Fazioli,grand,F308,10,Pyramid Mahogany or Macassar Satin/Polish,"$392,900"
...,...,...,...,...,...,...
994,Blüthner,grand,4 Senator,6,Jacaranda w/Leather,"$172,280"
995,Blüthner,grand,4 Wilhelm II,6,Black Polish/Satin,"$171,198"
996,Blüthner,grand,4 Wilhelm II,6,"Wilhelm II Walnut, Mahogany, Polish","$184,814"
997,Blüthner,grand,4 Wilhelm II,6,Wilhelm II Burl Walnut Polish,"$203,865"
998,Blüthner,grand,4 Wilhelm II,6,Wilhelm II Pyramid Mahogany,"$203,865"

In [8]:
df['dimension'] = df['dimension'].apply(
    lambda x: float(x) * 30.48 if x.strip() != '' else None
)

In [9]:
driver.close()

In [10]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome()
driver.get('https://www.pianobuyer.com/new-piano-pricing')
import numpy as np

In [13]:
time.sleep(20)
vertical_click = driver.find_element(By.XPATH , '/html/body/div/div/div[5]/div/div/div/div[1]').click()
trs_vertical = driver.find_elements(By.XPATH , '//*[@id="comp-l3ncpcyh"]/div/div/table/tbody/tr')
print(len(trs))

1000

In [ ]:
brand = []
model = []
dimension = []
description = []
price = []
type = ['vertical']* 999
for i in range(1 , 1000):
    brand.append(trs[i].find_elements(By.XPATH, f'//*[@id="comp-l3ncpcyh"]/div/div/table/tbody/tr[{i}]/td[1]')[0].text)
    model.append(trs[i].find_elements(By.XPATH, f'//*[@id="comp-l3ncpcyh"]/div/div/table/tbody/tr[{i}]/td[2]')[0].text)
    dimension.append(trs[i].find_elements(By.XPATH, f'//*[@id="comp-l3ncpcyh"]/div/div/table/tbody/tr[{i}]/td[4]')[0].text)
    description.append(trs[i].find_elements(By.XPATH, f'//*[@id="comp-l3ncpcyh"]/div/div/table/tbody/tr[{i}]/td[5]')[0].text)
    price.append(trs[i].find_elements(By.XPATH, f'//*[@id="comp-l3ncpcyh"]/div/div/table/tbody/tr[{i}]/td[7]')[0].text)

In [ ]:
df2 = pd.DataFrame({"brand" : brand , "type" : type , "model" : model , "dimension" : dimension , "description" : description , "price" : price})

In [ ]:
df2

,brand,type,model,dimension,description,price
0,Irmler,vertical,Monique,49,Ebony Polish,"$13,750"
1,Irmler,vertical,Louis,49,Ebony Polish,"$13,750"
2,Irmler,vertical,Titus,49,Ebony Polish,"$13,750"
3,Irmler,vertical,Alexa,49,Ebony Polish,"$15,950"
4,Irmler,vertical,Carlo,49,Ebony Polish,"$15,950"
...,...,...,...,...,...,...
994,Brodmann,vertical,CE 118,47,Ebony Polish,"$11,890"
995,Brodmann,vertical,PE 130,52,Ebony Polish,"$22,190"
996,Brodmann,vertical,PE 126 Institutaional,49,Ebony Polish,"$17,490"
997,Sauter,vertical,122 Peter Maly Artes,48,Palisander or Macassar Polish,"$63,500"
998,Sauter,vertical,122 Peter Maly Artes,48,Ebony Polish,"$62,000"

In [ ]:
df2['dimension'] = df2['dimension'].apply(
    lambda x: float(x) * 2.54 if x.strip() != '' else None
)

In [ ]:
data = pd.concat([df, df2], ignore_index=True)

In [ ]:
data

,brand,type,model,dimension,description,price
0,Cristofori,grand,G62L,182.88,Ebony Satin,"$20,999"
1,Fazioli,grand,F308,304.80,Ebony Polish/Satin,"$302,000"
2,Fazioli,grand,F308,304.80,White or Red Polish/Satin,"$332,300"
3,Fazioli,grand,F308,304.80,"Walnut, Cherry, or Mahogany Satin/Polish","$362,500"
4,Fazioli,grand,F308,304.80,Pyramid Mahogany or Macassar Satin/Polish,"$392,900"
...,...,...,...,...,...,...
1993,Brodmann,vertical,CE 118,119.38,Ebony Polish,"$11,890"
1994,Brodmann,vertical,PE 130,132.08,Ebony Polish,"$22,190"
1995,Brodmann,vertical,PE 126 Institutaional,124.46,Ebony Polish,"$17,490"
1996,Sauter,vertical,122 Peter Maly Artes,121.92,Palisander or Macassar Polish,"$63,500"
1997,Sauter,vertical,122 Peter Maly Artes,121.92,Ebony Polish,"$62,000"

In [ ]:
data['price'] = data['price'].apply(lambda x: int (x.replace('$', '').replace(',', '')) if x.strip() != '' else None)

In [ ]:
data

,brand,type,model,dimension,description,price
0,Cristofori,grand,G62L,182.88,Ebony Satin,20999.0
1,Fazioli,grand,F308,304.80,Ebony Polish/Satin,302000.0
2,Fazioli,grand,F308,304.80,White or Red Polish/Satin,332300.0
3,Fazioli,grand,F308,304.80,"Walnut, Cherry, or Mahogany Satin/Polish",362500.0
4,Fazioli,grand,F308,304.80,Pyramid Mahogany or Macassar Satin/Polish,392900.0
...,...,...,...,...,...,...
1993,Brodmann,vertical,CE 118,119.38,Ebony Polish,11890.0
1994,Brodmann,vertical,PE 130,132.08,Ebony Polish,22190.0
1995,Brodmann,vertical,PE 126 Institutaional,124.46,Ebony Polish,17490.0
1996,Sauter,vertical,122 Peter Maly Artes,121.92,Palisander or Macassar Polish,63500.0
1997,Sauter,vertical,122 Peter Maly Artes,121.92,Ebony Polish,62000.0

In [ ]:
data

,brand,type,model,dimension,description,price
0,Cristofori,grand,G62L,182.88,Ebony Satin,20999.0
1,Fazioli,grand,F308,304.80,Ebony Polish/Satin,302000.0
2,Fazioli,grand,F308,304.80,White or Red Polish/Satin,332300.0
3,Fazioli,grand,F308,304.80,"Walnut, Cherry, or Mahogany Satin/Polish",362500.0
4,Fazioli,grand,F308,304.80,Pyramid Mahogany or Macassar Satin/Polish,392900.0
...,...,...,...,...,...,...
1993,Brodmann,vertical,CE 118,119.38,Ebony Polish,11890.0
1994,Brodmann,vertical,PE 130,132.08,Ebony Polish,22190.0
1995,Brodmann,vertical,PE 126 Institutaional,124.46,Ebony Polish,17490.0
1996,Sauter,vertical,122 Peter Maly Artes,121.92,Palisander or Macassar Polish,63500.0
1997,Sauter,vertical,122 Peter Maly Artes,121.92,Ebony Polish,62000.0

In [ ]:
data.to_csv('dataset_for_buy.csv' , index=False)

In [ ]:
data = pd.read_csv("dataset_for_buy.csv")

In [ ]:
data

,brand,type,model,dimension,description,price
0,Cristofori,grand,G62L,182.88,Ebony Satin,20999.0
1,Fazioli,grand,F308,304.80,Ebony Polish/Satin,302000.0
2,Fazioli,grand,F308,304.80,White or Red Polish/Satin,332300.0
3,Fazioli,grand,F308,304.80,"Walnut, Cherry, or Mahogany Satin/Polish",362500.0
4,Fazioli,grand,F308,304.80,Pyramid Mahogany or Macassar Satin/Polish,392900.0
...,...,...,...,...,...,...
1993,Brodmann,vertical,CE 118,119.38,Ebony Polish,11890.0
1994,Brodmann,vertical,PE 130,132.08,Ebony Polish,22190.0
1995,Brodmann,vertical,PE 126 Institutaional,124.46,Ebony Polish,17490.0
1996,Sauter,vertical,122 Peter Maly Artes,121.92,Palisander or Macassar Polish,63500.0
1997,Sauter,vertical,122 Peter Maly Artes,121.92,Ebony Polish,62000.0

In [ ]:
grouping = data.groupby('description')
print(grouping['description'].value_counts())

description
Academy Ebony Polish                              1
African Pommele Polish                            6
Alder Polish                                      2
Amberwood Polish                                  6
Amboyna Polish                                    7
                                                 ..
Wood Veneer Upcharge                              1
Ziricote Polish                                   6
Ziricote Veneer                                   1
iPiano Hybrid, Ebony Polish w/Mahogany Accents    1
iPiano Hybrid, White Polish                       1
Name: count, Length: 308, dtype: int64

In [ ]:
import re
def preprocess(text):
    text = re.sub(r'[^\w\s/]', '', str(text).lower())
    tokens = re.split(r'[\s/]+', text)
    return [token for token in tokens if token and token != 'or']

data['description_array'] = data['description'].apply(preprocess)

In [ ]:
data

,brand,type,model,dimension,description,price,description_array
0,Cristofori,grand,G62L,182.88,Ebony Satin,20999.0,"[ebony, satin]"
1,Fazioli,grand,F308,304.80,Ebony Polish/Satin,302000.0,"[ebony, polish, satin]"
2,Fazioli,grand,F308,304.80,White or Red Polish/Satin,332300.0,"[white, red, polish, satin]"
3,Fazioli,grand,F308,304.80,"Walnut, Cherry, or Mahogany Satin/Polish",362500.0,"[walnut, cherry, mahogany, satin, polish]"
4,Fazioli,grand,F308,304.80,Pyramid Mahogany or Macassar Satin/Polish,392900.0,"[pyramid, mahogany, macassar, satin, polish]"
...,...,...,...,...,...,...,...
1993,Brodmann,vertical,CE 118,119.38,Ebony Polish,11890.0,"[ebony, polish]"
1994,Brodmann,vertical,PE 130,132.08,Ebony Polish,22190.0,"[ebony, polish]"
1995,Brodmann,vertical,PE 126 Institutaional,124.46,Ebony Polish,17490.0,"[ebony, polish]"
1996,Sauter,vertical,122 Peter Maly Artes,121.92,Palisander or Macassar Polish,63500.0,"[palisander, macassar, polish]"
1997,Sauter,vertical,122 Peter Maly Artes,121.92,Ebony Polish,62000.0,"[ebony, polish]"

In [ ]:
def extract_finish(tokens):
    return [t for t in tokens if t in {'satin', 'polish'}]

data['finish'] = data['description_array'].apply(extract_finish)

In [ ]:
data

,brand,type,model,dimension,description,price,description_array,finish
0,Cristofori,grand,G62L,182.88,Ebony Satin,20999.0,"[ebony, satin]",[satin]
1,Fazioli,grand,F308,304.80,Ebony Polish/Satin,302000.0,"[ebony, polish, satin]","[polish, satin]"
2,Fazioli,grand,F308,304.80,White or Red Polish/Satin,332300.0,"[white, red, polish, satin]","[polish, satin]"
3,Fazioli,grand,F308,304.80,"Walnut, Cherry, or Mahogany Satin/Polish",362500.0,"[walnut, cherry, mahogany, satin, polish]","[satin, polish]"
4,Fazioli,grand,F308,304.80,Pyramid Mahogany or Macassar Satin/Polish,392900.0,"[pyramid, mahogany, macassar, satin, polish]","[satin, polish]"
...,...,...,...,...,...,...,...,...
1993,Brodmann,vertical,CE 118,119.38,Ebony Polish,11890.0,"[ebony, polish]",[polish]
1994,Brodmann,vertical,PE 130,132.08,Ebony Polish,22190.0,"[ebony, polish]",[polish]
1995,Brodmann,vertical,PE 126 Institutaional,124.46,Ebony Polish,17490.0,"[ebony, polish]",[polish]
1996,Sauter,vertical,122 Peter Maly Artes,121.92,Palisander or Macassar Polish,63500.0,"[palisander, macassar, polish]",[polish]
1997,Sauter,vertical,122 Peter Maly Artes,121.92,Ebony Polish,62000.0,"[ebony, polish]",[polish]

In [ ]:
def remove_finish(tokens):
    return [t for t in tokens if t not in {'satin', 'polish'}]

data['description_array'] = data['description_array'].apply(remove_finish)

In [ ]:
data

,brand,type,model,dimension,description,price,description_array,finish
0,Cristofori,grand,G62L,182.88,Ebony Satin,20999.0,[ebony],[satin]
1,Fazioli,grand,F308,304.80,Ebony Polish/Satin,302000.0,[ebony],"[polish, satin]"
2,Fazioli,grand,F308,304.80,White or Red Polish/Satin,332300.0,"[white, red]","[polish, satin]"
3,Fazioli,grand,F308,304.80,"Walnut, Cherry, or Mahogany Satin/Polish",362500.0,"[walnut, cherry, mahogany]","[satin, polish]"
4,Fazioli,grand,F308,304.80,Pyramid Mahogany or Macassar Satin/Polish,392900.0,"[pyramid, mahogany, macassar]","[satin, polish]"
...,...,...,...,...,...,...,...,...
1993,Brodmann,vertical,CE 118,119.38,Ebony Polish,11890.0,[ebony],[polish]
1994,Brodmann,vertical,PE 130,132.08,Ebony Polish,22190.0,[ebony],[polish]
1995,Brodmann,vertical,PE 126 Institutaional,124.46,Ebony Polish,17490.0,[ebony],[polish]
1996,Sauter,vertical,122 Peter Maly Artes,121.92,Palisander or Macassar Polish,63500.0,"[palisander, macassar]",[polish]
1997,Sauter,vertical,122 Peter Maly Artes,121.92,Ebony Polish,62000.0,[ebony],[polish]

In [ ]:
def remove_last_word(text):
    if pd.isna(text):
        return text
    return text.rsplit(' ', 1)[0] if ' ' in text else text

data['description_array_color'] = data['description'].apply(remove_last_word)
data

,brand,type,model,dimension,description,price,description_array,finish,description_array_color
0,Cristofori,grand,G62L,182.88,Ebony Satin,20999.0,[ebony],[satin],Ebony
1,Fazioli,grand,F308,304.80,Ebony Polish/Satin,302000.0,[ebony],"[polish, satin]",Ebony
2,Fazioli,grand,F308,304.80,White or Red Polish/Satin,332300.0,"[white, red]","[polish, satin]",White or Red
3,Fazioli,grand,F308,304.80,"Walnut, Cherry, or Mahogany Satin/Polish",362500.0,"[walnut, cherry, mahogany]","[satin, polish]","Walnut, Cherry, or Mahogany"
4,Fazioli,grand,F308,304.80,Pyramid Mahogany or Macassar Satin/Polish,392900.0,"[pyramid, mahogany, macassar]","[satin, polish]",Pyramid Mahogany or Macassar
...,...,...,...,...,...,...,...,...,...
1993,Brodmann,vertical,CE 118,119.38,Ebony Polish,11890.0,[ebony],[polish],Ebony
1994,Brodmann,vertical,PE 130,132.08,Ebony Polish,22190.0,[ebony],[polish],Ebony
1995,Brodmann,vertical,PE 126 Institutaional,124.46,Ebony Polish,17490.0,[ebony],[polish],Ebony
1996,Sauter,vertical,122 Peter Maly Artes,121.92,Palisander or Macassar Polish,63500.0,"[palisander, macassar]",[polish],Palisander or Macassar
1997,Sauter,vertical,122 Peter Maly Artes,121.92,Ebony Polish,62000.0,[ebony],[polish],Ebony

In [ ]:
def rePreprocess(text):
    if pd.isna(text):
        return text
    text = str(text).lower()
    text = re.sub(r'\sor\s', '/', text)     
    text = text.replace(',', '/')          
    text = re.sub(r'[^\w\s/]', '', text) 
    tokens = text.split('/')
    return [token.strip() for token in tokens if token.strip()]

data['description_array_color_x'] = data['description_array_color'].apply(rePreprocess)
data.head(20)

,brand,type,model,dimension,description,price,description_array,finish,description_array_color,description_array_color_x
0,Cristofori,grand,G62L,182.88,Ebony Satin,20999.0,[ebony],[satin],Ebony,[ebony]
1,Fazioli,grand,F308,304.80,Ebony Polish/Satin,302000.0,[ebony],"[polish, satin]",Ebony,[ebony]
2,Fazioli,grand,F308,304.80,White or Red Polish/Satin,332300.0,"[white, red]","[polish, satin]",White or Red,"[white, red]"
3,Fazioli,grand,F308,304.80,"Walnut, Cherry, or Mahogany Satin/Polish",362500.0,"[walnut, cherry, mahogany]","[satin, polish]","Walnut, Cherry, or Mahogany","[walnut, cherry, mahogany]"
4,Fazioli,grand,F308,304.80,Pyramid Mahogany or Macassar Satin/Polish,392900.0,"[pyramid, mahogany, macassar]","[satin, polish]",Pyramid Mahogany or Macassar,"[pyramid mahogany, macassar]"
5,Fazioli,grand,F308,304.80,"Mahogany, California Walnut, or Sequoia Briars...",422900.0,"[mahogany, california, walnut, sequoia, briars]","[satin, polish]","Mahogany, California Walnut, or Sequoia Briars","[mahogany, california walnut, sequoia briars]"
6,Fazioli,grand,F308,304.80,Olive Polish/Satin,444100.0,[olive],"[polish, satin]",Olive,[olive]
7,Irmler,grand,F148,121.92,Ebony Polish,24981.0,[ebony],[polish],Ebony,[ebony]
8,Irmler,grand,F148,121.92,White Polish,26125.0,[white],[polish],White,[white]
9,Irmler,grand,F148,121.92,Mahogany Polish,26411.0,[mahogany],[polish],Mahogany,[mahogany]
10,Irmler,grand,F148,121.92,Walnut Polish,26411.0,[walnut],[polish],Walnut,[walnut]
11,Irmler,grand,F160,152.40,Ebony Polish,27555.0,[ebony],[polish],Ebony,[ebony]
12,Irmler,grand,F160,152.40,White Polish,30129.0,[white],[polish],White,[white]
13,Irmler,grand,F160,152.40,Mahogany Polish,28699.0,[mahogany],[polish],Mahogany,[mahogany]
14,Irmler,grand,F160,152.40,Walnut Polish,28699.0,[walnut],[polish],Walnut,[walnut]
15,Irmler,grand,F188,182.88,Ebony Polish,33132.0,[ebony],[polish],Ebony,[ebony]
16,Irmler,grand,F188,182.88,White Polish,36278.0,[white],[polish],White,[white]
17,Irmler,grand,F188,182.88,Mahogany Polish,36207.0,[mahogany],[polish],Mahogany,[mahogany]
18,Irmler,grand,F188,182.88,Walnut Polish,36207.0,[walnut],[polish],Walnut,[walnut]
19,Irmler,grand,F160 E,152.40,Ebony Polish,32847.0,[ebony],[polish],Ebony,[ebony]

In [ ]:
data = data.drop(['description', 'description_array' , 'description_array_color'], axis=1)

In [ ]:
data = data.rename(columns={'description_array_color_x': 'color_array'})

In [ ]:
data = data[['brand', 'type', 'model' , 'dimension' , 'color_array' , 'finish' , 'price']]

In [ ]:
data

,brand,type,model,dimension,color_array,finish,price
0,Cristofori,grand,G62L,182.88,[ebony],[satin],20999.0
1,Fazioli,grand,F308,304.80,[ebony],"[polish, satin]",302000.0
2,Fazioli,grand,F308,304.80,"[white, red]","[polish, satin]",332300.0
3,Fazioli,grand,F308,304.80,"[walnut, cherry, mahogany]","[satin, polish]",362500.0
4,Fazioli,grand,F308,304.80,"[pyramid mahogany, macassar]","[satin, polish]",392900.0
...,...,...,...,...,...,...,...
1993,Brodmann,vertical,CE 118,119.38,[ebony],[polish],11890.0
1994,Brodmann,vertical,PE 130,132.08,[ebony],[polish],22190.0
1995,Brodmann,vertical,PE 126 Institutaional,124.46,[ebony],[polish],17490.0
1996,Sauter,vertical,122 Peter Maly Artes,121.92,"[palisander, macassar]",[polish],63500.0
1997,Sauter,vertical,122 Peter Maly Artes,121.92,[ebony],[polish],62000.0

In [ ]:
color_counts = data.explode('color_array')['color_array'].value_counts()
print(color_counts)

color_array
ebony                         638
mahogany                      277
white                         208
walnut                        206
cherry                        104
                             ...
ebony polish bubinga            1
the teague ebony polish         1
jubilee walnut                  1
satin spirio only               1
two tone polish apple tree      1
Name: count, Length: 249, dtype: int64

In [ ]:
data.to_csv('prefinal_dataset.csv')

In [ ]:
main_colors = ['ebony' , 'mahogany' , 'white' , 'walnut' , 'cherry' , 'bubinga' , 'vavona' , 'yew' , 'rosewood' , 'chrome' , 'pommele' ,'black',
               'nickel' , 'oak' , 'makassar' , 'burl' , 'macassar' ,'extraordinary veneers' , 'special veneers' ,'ordinary veneers' ,'maple']
def change_color(text):
    if isinstance(text, float) and pd.isna(text):  
        return text
    
    if isinstance(text, list):
        updated_text = []
        for item in text:
            updated_item = item  
            for color in main_colors:
                if color in item:  
                    updated_item = color  
                    break  
            updated_text.append(updated_item)
        return updated_text
    return text
data['color_array_x'] = data['color_array'].apply(change_color)
data.head(10)

,brand,type,model,dimension,color_array,finish,price,color_array_x
0,Cristofori,grand,G62L,182.88,[ebony],[satin],20999.0,[ebony]
1,Fazioli,grand,F308,304.80,[ebony],"[polish, satin]",302000.0,[ebony]
2,Fazioli,grand,F308,304.80,"[white, red]","[polish, satin]",332300.0,"[white, red]"
3,Fazioli,grand,F308,304.80,"[walnut, cherry, mahogany]","[satin, polish]",362500.0,"[walnut, cherry, mahogany]"
4,Fazioli,grand,F308,304.80,"[pyramid mahogany, macassar]","[satin, polish]",392900.0,"[mahogany, macassar]"
5,Fazioli,grand,F308,304.80,"[mahogany, california walnut, sequoia briars]","[satin, polish]",422900.0,"[mahogany, walnut, sequoia briars]"
6,Fazioli,grand,F308,304.80,[olive],"[polish, satin]",444100.0,[olive]
7,Irmler,grand,F148,121.92,[ebony],[polish],24981.0,[ebony]
8,Irmler,grand,F148,121.92,[white],[polish],26125.0,[white]
9,Irmler,grand,F148,121.92,[mahogany],[polish],26411.0,[mahogany]

In [ ]:
color_counts = data.explode('color_array_x')['color_array_x'].value_counts()
print(color_counts.to_string())

color_array_x
ebony                                             879
walnut                                            374
mahogany                                          374
white                                             258
cherry                                            126
bubinga                                            47
rosewood                                           35
vavona                                             35
yew                                                33
oak                                                22
chrome                                             21
pommele                                            21
black                                              19
macassar                                           19
burl                                               17
ordinary veneers                                   17
special veneers                                    17
maple                                              16
extraordinary veneers                              15
nickel                                             14
palisander                                         12
makassar                                           12
indian apple                                       11
ral colors polish or                               10
wenge                                              10
camphor                                             9
pomele polish or                                    9
madronna                                            9
silver                                              8
ziricote                                            8
beech                                               7
amboyna                                             7
red                                                 7
sequoia briars                                      7
olive                                               7
light ivory                                         7
alder                                               6
sterling                                            6
twist  change                                       6
padauk                                              6
figured sycamore                                    6
koa                                                 6
amberwood                                           6
custom color                                        6
color pops                                          6
swiss                                               5
satin incl sordino pedal and mozart                 5
with qrs system                                     4
jacaranda                                           4
studio lacquer                                      4
santos                                              4
brass                                               3
crystal edition                                     3
spirio  r playback  record player piano system      3
spade                                               3
skyline                                             3
gold                                                3
fire engine red                                     3
dynasty                                             3
pyramid                                             3
soundboard                                          3
gray polish w                                       3
satin or                                            2
wilhelm ii pyramid                                  2
pomelle                                             2
silent piano sh2 system                             2
evolution bose moontime sound system                2
ash                                                 2
extraordinary venerrs polish or                     2
ipiano hybrid                                       2
klimt tree of                                       2
evolution home moontime sound                       2
spirio play playback only player piano system       2
satin w                                             2
french                                              1
bench not                                           1
continental beech                                   1
blue polish w                                       1
sostenuto                                           1
rose gold sandalwood                                1
continental polished                                1
blue                                                1
model by robert                                     1
satin spirio only                                   1
red polish w                                        1
green apple                                         1
georgian satin                                      1
mozart rail                                         1
and                                                 1
ral colors polish                                   1
marquetry                                           1
disklavier enspire pro                              1
fire red                                            1
french provincial lacquer semigloss                 1
nichetto red duet spirio playback  record only      1
noe ivory                                           1
burgundy                                            1
deep                                                1
qing ming                                           1
ny                                                  1
great wall                                          1
duet option                                         1
wood veneer                                         1
color                                               1
paldao                                              1
eukalyptus                                          1
zebrano                                             1
cambridge collection                                1
crystal transparent plexiglass with silver          1
tiger striped sandalwood                            1
golden silk phoebe                                  1
two tone polish apple tree                          1

In [ ]:
data.to_csv('preprefinal_dataset.csv')

In [ ]:
exploded = data.explode('color_array_x')
color_counts = exploded['color_array_x'].value_counts()
rare_colors = color_counts[color_counts < 12].index
exploded['color_array_x'] = exploded['color_array_x'].apply(lambda x: 'other' if x in rare_colors else x)
data['color_array_cleaned'] = exploded.groupby(exploded.index)['color_array_x'].apply(list)

In [ ]:
color_counts = data.explode('color_array_cleaned')['color_array_cleaned'].value_counts()
print(color_counts)

color_array_cleaned
ebony                    879
walnut                   374
mahogany                 374
other                    291
white                    258
cherry                   126
bubinga                   47
rosewood                  35
vavona                    35
yew                       33
oak                       22
chrome                    21
pommele                   21
black                     19
macassar                  19
ordinary veneers          17
special veneers           17
burl                      17
maple                     16
extraordinary veneers     15
nickel                    14
palisander                12
makassar                  12
Name: count, dtype: int64

In [ ]:
data

,brand,type,model,dimension,color_array,finish,price,color_array_x,color_array_cleaned
0,Cristofori,grand,G62L,182.88,[ebony],[satin],20999.0,[ebony],[ebony]
1,Fazioli,grand,F308,304.80,[ebony],"[polish, satin]",302000.0,[ebony],[ebony]
2,Fazioli,grand,F308,304.80,"[white, red]","[polish, satin]",332300.0,"[white, red]","[white, other]"
3,Fazioli,grand,F308,304.80,"[walnut, cherry, mahogany]","[satin, polish]",362500.0,"[walnut, cherry, mahogany]","[walnut, cherry, mahogany]"
4,Fazioli,grand,F308,304.80,"[pyramid mahogany, macassar]","[satin, polish]",392900.0,"[mahogany, macassar]","[mahogany, macassar]"
...,...,...,...,...,...,...,...,...,...
1993,Brodmann,vertical,CE 118,119.38,[ebony],[polish],11890.0,[ebony],[ebony]
1994,Brodmann,vertical,PE 130,132.08,[ebony],[polish],22190.0,[ebony],[ebony]
1995,Brodmann,vertical,PE 126 Institutaional,124.46,[ebony],[polish],17490.0,[ebony],[ebony]
1996,Sauter,vertical,122 Peter Maly Artes,121.92,"[palisander, macassar]",[polish],63500.0,"[palisander, macassar]","[palisander, macassar]"
1997,Sauter,vertical,122 Peter Maly Artes,121.92,[ebony],[polish],62000.0,[ebony],[ebony]

In [ ]:
data = data.drop(['color_array', 'color_array_x'], axis=1)

In [ ]:
data = data.rename(columns={'color_array_cleaned': 'color_array'})

In [ ]:
data = data[['brand', 'type', 'model' , 'dimension' , 'color_array' , 'finish' , 'price']]
data

,brand,type,model,dimension,color_array,finish,price
0,Cristofori,grand,G62L,182.88,[ebony],[satin],20999.0
1,Fazioli,grand,F308,304.80,[ebony],"[polish, satin]",302000.0
2,Fazioli,grand,F308,304.80,"[white, other]","[polish, satin]",332300.0
3,Fazioli,grand,F308,304.80,"[walnut, cherry, mahogany]","[satin, polish]",362500.0
4,Fazioli,grand,F308,304.80,"[mahogany, macassar]","[satin, polish]",392900.0
...,...,...,...,...,...,...,...
1993,Brodmann,vertical,CE 118,119.38,[ebony],[polish],11890.0
1994,Brodmann,vertical,PE 130,132.08,[ebony],[polish],22190.0
1995,Brodmann,vertical,PE 126 Institutaional,124.46,[ebony],[polish],17490.0
1996,Sauter,vertical,122 Peter Maly Artes,121.92,"[palisander, macassar]",[polish],63500.0
1997,Sauter,vertical,122 Peter Maly Artes,121.92,[ebony],[polish],62000.0

In [ ]:
data.to_csv("final_dataset.csv")

In [ ]:
data.isna().sum()

brand           1
type            0
model           1
dimension      20
color_array     0
finish          0
price          55
dtype: int64

In [16]:
data = pd.read_csv("final_dataset.csv")

In [17]:
data['price'] = data['price'].fillna(data.groupby(['type' , 'brand'])['price'].transform('mean'))

In [18]:
data.isna().sum()

Unnamed: 0      0
brand           1
type            0
model           1
dimension      20
color_array     0
finish          0
price          50
dtype: int64

In [19]:
data['price'] = data['price'].fillna(data.groupby('type')['price'].transform('mean'))

In [20]:
data.isna().sum()

Unnamed: 0      0
brand           1
type            0
model           1
dimension      20
color_array     0
finish          0
price           0
dtype: int64

In [21]:
data['dimension'] = data['dimension'].fillna(data.groupby(['type' , 'model'])['dimension'].transform('mean'))

In [22]:
data.isna().sum()

Unnamed: 0      0
brand           1
type            0
model           1
dimension      17
color_array     0
finish          0
price           0
dtype: int64

In [23]:
data['dimension'] = data['dimension'].fillna(data.groupby('type')['dimension'].transform('mean'))

In [24]:
data = data.dropna()

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1997 entries, 0 to 1997
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1997 non-null   int64
 1   brand        1997 non-null   object
 2   type         1997 non-null   object
 3   model        1997 non-null   object
 4   dimension    1997 non-null   float64
 5   color_array  1997 non-null   object
 6   finish       1997 non-null   object
 7   price        1997 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 140.4+ KB

In [29]:
data.to_csv("data.csv" , index=False)

In [30]:
data2 = pd.read_csv("data.csv")

In [31]:
data2

,Unnamed: 0,brand,type,model,dimension,color_array,finish,price
0,0,Cristofori,grand,G62L,182.88,['ebony'],['satin'],20999.0
1,1,Fazioli,grand,F308,304.80,['ebony'],"['polish', 'satin']",302000.0
2,2,Fazioli,grand,F308,304.80,"['white', 'other']","['polish', 'satin']",332300.0
3,3,Fazioli,grand,F308,304.80,"['walnut', 'cherry', 'mahogany']","['satin', 'polish']",362500.0
4,4,Fazioli,grand,F308,304.80,"['mahogany', 'macassar']","['satin', 'polish']",392900.0
...,...,...,...,...,...,...,...,...
1992,1993,Brodmann,vertical,CE 118,119.38,['ebony'],['polish'],11890.0
1993,1994,Brodmann,vertical,PE 130,132.08,['ebony'],['polish'],22190.0
1994,1995,Brodmann,vertical,PE 126 Institutaional,124.46,['ebony'],['polish'],17490.0
1995,1996,Sauter,vertical,122 Peter Maly Artes,121.92,"['palisander', 'macassar']",['polish'],63500.0
1996,1997,Sauter,vertical,122 Peter Maly Artes,121.92,['ebony'],['polish'],62000.0

In [39]:
data2 = data2.drop(['Unnamed: 0'], axis=1)

In [40]:
data2.to_csv("data.csv" , index=False)